spring:
  application:
    name: AirportItemStorage
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  web:
    swaggerUrl: http://localhost:${server.port}/swagger-ui/index.html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      encoding: UTF-8
      mode: always
      schema-locations:
        - classpath:sql/start.sql
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.qq.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: org.code.airportitemstorage.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:

custom-quartz:
  jobs:
    - name: ScheduleAutoCheckOrderForEmailJob
      group: emailJob
      cron: "0 */5 * * * ?"
      jobData:
        enableOrderCheckForEmail: true
    - name: ScheduleAutoHandleExpiredOrderJob
      group: expiredOrderJob
      cron: "0 */10 * * * ?"
      jobData:
        enableExpiredOrder: true
